name: Deploy Foam website

on:
  push:

jobs:
  deploy-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1

      - name: Install website dependencies
        run: npm install
        working-directory: _layouts
      - name: Build website
        run: npm run build -- --prefix-paths
        working-directory: _layouts

      - name: Deploy to the gh-pages branch
        # only deploy when the main branch has some changes
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_layouts/public
